### PR TITLE
Typage

### PR DESCRIPTION
**Pull request by librelois**

### CODE REVIEW

**Comment by c-geek** [comment]
Thanks for the PR, please **do not integrate it yet**. This code will be part of Duniter 1.7.x.

**Comment by librelois** [comment]
Understood :)

**Comment by librelois** [comment]
It's ready to merge

**Comment by c-geek** [comment]
I will have a look today, there are a few things I need to check.

**Comment by c-geek** [comment]
It seems all OK to me, except the sandbox which needs to keep control over the issuer field of an identity, a certification and a membership, which is not `issuers` but `pubkey`, `from` and `issuer`.

**Comment by c-geek** [comment]
I just wait the CI tests and merge the PR.

**Comment by c-geek** [comment]
I was wrong, your code was already good! Sorry for polluting :disappointed:

**Comment by librelois** [comment]
yes I have modified the logic so that any Duniter document is only a table of issuers, I find it more elegant

**Pull request merged**
