### PR TITLE
[enh] #530: update node modules dependecies.

### PR DESCRIPTION
**Pull request by M5oul**
I update all dependencies except `sqlite3`.
All seems to works well. I tested it with Node 4.5.
Ok, all CI tests passed.
@c-geek, I let you merge this PR as I could miss something.

### CODE REVIEW

**Comment by modulix** [comment]
FYI: About compatibility...
Very god job guys !
I have tried to run a duniter node with nodejs-5.10.1, seems ok.
The latest node i have tried is 6.3.1, and it seems to run well also without errors/warnings ;-)
So don't worry, be happy !

**Comment by modulix** [comment]
With version > 6.3.1 i get a lot of warnings:

```
$ node ./bin/duniter start
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x3d678fc5 <JS Object>#0#
... [ very long stack trace ]
```

**Comment by M5oul** [comment]
Yep, thanks a lot for testing :smile_cat: 

In fact, [modules needs to be updates to handle Node.js v6](https://github.com/duniter/duniter/issues/496)

**Comment by c-geek** [comment]
OK I will have a look tomorrow.

The best would be to merge this PR on a new branch and make a pre-release using the automated release tool: `./release.sh pre 0.31.0a1`

@Moul, you can try to do it if you want, you don't need me for that!

**Comment by M5oul** [comment]
Ok, I did a [release](https://github.com/duniter/duniter/releases).
I manually created a release, so it creates small errors. But it's ok.
It's an awesome tool which automatically generate builds :smile: 

---

Builds works fine.

**Comment by c-geek** [comment]
We have to test Windows to be sure, because most of the time Linux builds has no particular problems.

**Comment by c-geek** [comment]
It just works, you can merge if you want.

**Comment by M5oul** [comment]
Done, merged in `master` and `dev` branches.

**Pull request merged**
