### PR TITLE
Handle Node.js v8.x

### PR DESCRIPTION
**Pull request by M5oul**
#689 
It works fine on my side since now.
But, I assume you will to make some tests.
As, Node Webkit may not works.
And does sqlite3 upgrade does not breaks things.
I opened it for other developers to test it and to allows me use it on my side with Fedora 27.

### CODE REVIEW

**Comment by M5oul** [comment]
The check seems to be linked to Windows and sqlite3.

**Comment by c-geek** [comment]
Please do not upgrade sqlite3, this is a very sensitive module.

The checks failed because of a bug in duniter `dev` branch: https://travis-ci.org/duniter/duniter/branches

**Comment by M5oul** [comment]
Could I use it on my side?
May it breaks something on my system?

**Comment by c-geek** [comment]
You can do whatever you want on your side, but I cannot guarantee to you it will work.

About your PR: it is not mergeable, we will eventually pick just your commit when we accept Node.js 8.

**Comment by c-geek** [comment]
https://git.duniter.org/nodes/typescript/duniter/merge_requests/1140

**Pull request closed without merging**
