### PR TITLE
 Add the packaging metadata to build the duniter snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest dunier in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress.

### CODE REVIEW

**Comment by elopio** [comment]
Hello!

I recently found your project, and took the chance last week to give it a try while testing a new snapcraft release. If you haven't heard about snaps before, here's a lot of info: https://snapcraft.io/

I think it would be great if you push it to the store. This package only has the server, but if you like the idea, the tools, and exposing duniter to all the Ubuntu users, we can talk about making snaps for cesium and the other components.

To test this in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/duniter
    $ cd duniter
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous --devmode
    $ duniter config --port 8000 --ipv4 127.0.0.1
    $ duniter start
    $ sensible-browser localhost:8000

If you have any questions, please let me kno.

pura vida.

**Comment by M5oul** [comment]
Could I test this on Fedora?
I installed [`snapd` package](https://apps.fedoraproject.org/packages/snapd).
Then, no `snapcraft` command exist.

**Comment by elopio** [comment]
@M5oul not yet. You can't install the snapcraft snap in Fedora because it uses classic confinement, but you will be able to do it soon. There's a team here polishing all the details of cross-distro snaps.

Maybe, you can install the lxd snap in there, and start an ubuntu xenial container. I haven't tried it, though. I have a Fedora 25 around so let me know if you have any issues and I'll take a look.

**Comment by c-geek** [comment]
That's definitively a good idea. I will have a check in the coming days.

**Comment by c-geek** [comment]
Note: migrated to: https://git.duniter.org/nodes/typescript/duniter/merge_requests/965

**Pull request closed without merging**
